### ISSUE TITLE
Presenter surivival

### ISSUE THREAD

**Issue by antonshkurenko** [benoitletondor/Android-Studio-MVP-template#1]
Is it possible to add template for this [strategy](https://medium.com/@czyrux/presenter-surviving-orientation-changes-with-loaders-6da6d86ffbbf#.1vzew0nva)?

**Comment by antonshkurenko** [comment]
Sorry, didn't understood

**Comment by antonshkurenko** [comment]
Sorry, for this "panic", I logged some methods and here is result:

```
D/MainPresenterImpl: MainPresenterImpl: creation: 292446359
D/MainActivity: onCreate: 747806087
D/MainPresenterImpl: onStart: view: 747806087, presenter: 292446359
D/MainPresenterImpl: MainPresenterImpl: creation: 356988377
D/MainPresenterImpl: onRestoreState: view: 9452446, presenter: 356988377
D/MainActivity: onCreate: 9452446
D/MainPresenterImpl: onStart: view: 9452446, presenter: 356988377
```

I've heard, that Android N multi-window feature will trigger same behavior as Screen Rotating, how to save data/presenter between screen rotation since it recreates after every activity recreation?

Or you suggest to save everything in bundle?

**Comment by benoitletondor** [comment]
Hi Tony,

Indeed the presenter lifecycle is tied to its activity so if the activity is destroyed then its presenter too. 

You have 3 ways (maybe more) to handle that problem:
- Easiest: Declare in your manifest to not recreate your activity on rotation/resize/whatever with the `configChange` tag
- Safest: Save your data into the bundle on `onSaveInstanceState` and restore it on `onRestoreState`, this is the exact purpose of those methods but it has limitations (like if you're in the middle of a data loading process)
- Advanced: Use your presenter as a loader to survive activity recreation, more on that [here](https://medium.com/@czyrux/presenter-surviving-orientation-changes-with-loaders-6da6d86ffbbf#.2llsbg7hu)

Hope it helps!

**Comment by benoitletondor** [comment]
Hey @tonyshkurenko,

Just wanted to let your know that the last version I pushed a few days ago now supports presenter survival.

More on that on the README.

Best
