### ISSUE TITLE
Right way to access presenter

### ISSUE THREAD

**Issue by ghost** [benoitletondor/Android-Studio-MVP-template#12]
Hi.
Thank for great work.
In generated Activity code you write "Your presenter is available using the mPresenter variable" but i confused what is **mPresenterFactory** for?
I should **mPresenterFactory.create()** or **mPresenter**?

**Comment by benoitletondor** [comment]
Hi @handinux 

The presenter factory is here to generate a new presenter when needed (basically every time you show a new Activity) but you don't interact with it directly. The job is done by the framework and all you have to care about is using your presenter using the `mPresenter` variable.

Is that clear enough?

**Comment by ghost** [comment]
Wow thank you for fast reply @benoitletondor
Yes it clear now.
