### ISSUE TITLE
Use along with RxAndroid

### ISSUE THREAD

**Issue by ghost** [benoitletondor/Android-Studio-MVP-template#13]
Hi
I want call APIs in my code but i confused where i should use RxAndroid and where i should unsubscribe subscriptions.

**Comment by benoitletondor** [comment]
Hi,

You should use Rx everywhere in the presenter, just ensure that `mView` is not null after work is done (cause it can sometimes).

You should unsubscribe on the presenter `onPresenterDestroyed` method. This method will be called only when the view is gone and won't be called in case of a configuration change (on a rotation for exemple).

Let me know if something's not clear.
