### ISSUE TITLE
DialogFragment

### ISSUE THREAD

**Issue by ghost** [benoitletondor/Android-Studio-MVP-template#16]
hi
how can i make a DialogFragment extend BaseFragment?

**Comment by benoitletondor** [comment]
Hi, 

This template doesn't cover the DialogFragment but I made a library that you can include into your repo that contains all boilerplate of this MVP template + the one of DialogFragment: https://github.com/benoitletondor/mvp-core

It's the same code between this template and this library and it comes as an handy gradle dep so it's easier to use.

Let me know if something's not clear.

**Comment by ghost** [comment]
Thank you so much :)
