### ISSUE TITLE
Context in ViewModule

### ISSUE THREAD

**Issue by ghost** [benoitletondor/Android-Studio-MVP-template#17]
Hi
How can i access context in ViewModule classes?

**Comment by benoitletondor** [comment]
I'm not sure I get your question, does ViewModule mean `Presenter`?

**Comment by ghost** [comment]
Module files those annotated with `@module` and `@provide`. I want use them to provide `Dialog` to inject into View then I need Activity context.

**Comment by benoitletondor** [comment]
I think there's a misunderstanding about how you're supposed to use Modules in an MVP architectures.
The `View` is supposed to take care of everything `Context` related, including building and displaying `Dialog`s

**Comment by ghost** [comment]
Thanks. You cleared me.
