### ISSUE TITLE
androidX compatability

### ISSUE THREAD

**Issue by ghost** [benoitletondor/Android-Studio-MVP-template#18]
hi
how to change imports to support androidX?

thanks

**Comment by benoitletondor** [comment]
Hi, 

We would need to have a way to specify if we should use androidX or not as a part of the UI for creating a new view. 

That definitely needs some time to develop, if you want to dig into that feel free

**Comment by hoangvunam** [comment]
Just added a new pull request for this issue, please check.

**Comment by benoitletondor** [comment]
Hey there, thanks to @namhvcntt work, the [2.3 version](https://github.com/benoitletondor/Android-Studio-MVP-template/releases/tag/2.3) is now 
using AndroidX.

**Comment by handinux** [comment]
Thanks @namhvcntt and @benoitletondor
