### ISSUE TITLE
Do you have articles to explain how to use this mvp framework it？

### ISSUE THREAD

**Issue by leasual** [benoitletondor/Android-Studio-MVP-template#2]
Hi, benoitletondor,
Do you have articles to explain how to use this mvp framework it or some documentation？

thanks.

**Comment by benoitletondor** [comment]
Hi there,

How can I help you using it? What's not clear for you?

**Comment by leasual** [comment]
I carefully studied u2020 this project,after that，i noticed your framework relative is more interaction than the traditional framework MVP, and M,V,P three are decoupled, does this interaction is to reduce the burden of P, I do not know whether i understand it rightly?

**Comment by benoitletondor** [comment]
I'm sorry but I don't get your question :/
