### ISSUE TITLE
Is @Inject really needed in *InteractorImpl & *PresenterImpl constructors?

### ISSUE THREAD

**Issue by matoelorriaga** [benoitletondor/Android-Studio-MVP-template#4]
I've seen that `@Inject` is used in both Interactor & Presenter implementations:

```
@Inject
public MainPresenterImpl(@NonNull MainInteractor interactor) {
    mInteractor = interactor;
}

@Inject
public MainInteractorImpl(PokemonAPI pokemonAPI) {
    mPokemonAPI = pokemonAPI;
}
```

are those `@Inject` really necessary? why? both instances are already provided by *Module (in this case, MainModule)

```
@Provides
@ActivityScope
public MainInteractor provideInteractor(PokemonAPI pokemonAPI) {
    return new MainInteractorImpl(pokemonAPI);
}

@Provides
@ActivityScope
public PresenterFactory<MainPresenter> providePresenterFactory(@NonNull final MainInteractor interactor) {
    return new PresenterFactory<MainPresenter>() {
        @NonNull
        @Override
        public MainPresenter create() {
            return new MainPresenterImpl(interactor);
        }
    };
}
```

**Comment by benoitletondor** [comment]
Hi @matoelorriaga !

The Dagger 2 documentation says that whenever a constructor is made to be used by Dagger (via an `@Provides` method) it should be annotated with `@Inject`:  [https://google.github.io/dagger/users-guide.html](https://google.github.io/dagger/users-guide.html) (See "Declaring Dependencies")

I'm not sure whether it works without them or not, but if you feel like removing them and see what happen let me know how it goes ;)

**Comment by matoelorriaga** [comment]
Thanks for the quick answer!

If I remove both `@Inject`s, everything is still working as expected.. as far as I understand, `@Inject` in constructors is to tell Dagger "use this constructor when an instance of this type is required".. and `@Provides` methods are the same, but for classes we don't own (like Android specific classes).. 
So, I think that in this case is safe to remove it, but wanna be sure :)

Thanks again!

**Comment by benoitletondor** [comment]
If everything still works after you removed them then you're good to go, and I learned something :)

Thank you for testing it!
