### ISSUE TITLE
How to pass an extra from activity to presenter?

### ISSUE THREAD

**Issue by matoelorriaga** [benoitletondor/Android-Studio-MVP-template#5]
(Sorry if this is not the best place to ask questions)

I'm working on an application that has two screens:

- a list of pokemons (using a recyclerview)
- pokemon details

In the first screen, I configure the view in MainActivity.onCreate(), and then, inside MainPresenterImpl, I do:

```
@Override
public void onStart(boolean firstStart) {
    super.onStart(firstStart);

    // Your code here. Your view is available using mView and will not be null until next onStop()

    if (firstStart) {
        getPokemonNames(); // this method belongs to MainPresenter
    }
}
```

This works ok.

But, for the second screen, in order to call the server I need the id of the pokemon, so when I select a pokemon from the recyclerview, I start DetailsActivity and pass an EXTRA_POKEMON_ID in the intent.

Now, here is the problem: I do not have access to that id inside the presenter, so I'm not able to follow the same approach as before:

```
@Override
public void onStart(boolean firstStart) {
    super.onStart(firstStart);

    // Your code here. Your view is available using mView and will not be null until next onStop()

    if (firstStart) {
        // getPokemonDetails(id); // I do not have the id here
    } else {
        if (mInteractor.networkRequestInProgress()) {
            mView.showLoadingIndicator();
        }
        mView.showPokemonDetails(mPokemon);
    }
}
```

I tried to call the presenter inside DetailsActivity.onStart(), but doing that, the presenter is called each time the "configuration change" (like rotate the phone) and that is not ideal.

What's the proper way to handle a case like this?

**Comment by benoitletondor** [comment]
Hi @matoelorriaga 

To do that you can simply add a method to your view that expose the id, something like

```
public interface DetailsView {
    int getPokemonId()
}
```

The implementation in your DetailsActivity:

```
@Override
int getPokemonId() {
     return getIntent().getIntExtra(EXTRA_POKEMON_ID, -1);
}
```

And in the presenter:

```
int mPokemonId = -1;

@Override
public void onStart(boolean firstStart) {
    super.onStart(firstStart);

    if (mPokemonId == -1) {
        mPokemonId = mView.getPokemonId();
    }

    if (mInteractor.networkRequestInProgress()) {
        mView.showLoadingIndicator();
    }

    mView.showPokemonDetails(mPokemonId);
}
```

Does that makes sense?

**Comment by matoelorriaga** [comment]
I've added that method you suggested in `DetailsView` and now `onStart` inside `DetailsPresenterImpl` looks like this:

```
@Override
public void onStart(boolean firstStart) {
    super.onStart(firstStart);

    // Your code here. Your view is available using mView and will not be null until next onStop()

    if (firstStart) {
        int pokemonId = mView.getPokemonId();
        getPokemonDetails(pokemonId);
    } else {
        if (mInteractor.networkRequestInProgress()) {
            mView.showLoadingIndicator();
        }
        mView.showPokemonDetails(mPokemon);
    }
}
```

Works like a charm, thanks!

(sorry again, I know this is not the right place to ask questions)
